#ifndef MRTEST_H
#define MRTEST_H

void VecToSO3Test();
void JacobianSpaceTest();
void JacobianBodyTest();
void adTest();
void TransInvTest();
void RotInvTest();
void ScrewToAxisTest();
void FKInBodyTest();
void FKInSpaceTest();
void AxisAng6Test();
void MatrixLog6Test();
void DistanceToSO3Test();
void DistanceToSE3Test();
void TestIfSO3Test();
void TestIfSE3Test();
void IKinBodyTest();
void IKinSpaceTest();
void AdjointTest();
void InverseDynamicsTest();
void GravityForcesTest();
void MassMatrixTest();
void VelQuadraticForcesTest();
void EndEffectorForcesTest();
void ForwardDynamicsTest();
void EulerStepTest();
void ComputedTorqueTest();
void CubicTimeScalingTest();
void QuinticTimeScalingTest();
void JointTrajectoryTest();
void ScrewTrajectoryTest();
void CartesianTrajectoryTest();
void InverseDynamicsTrajectoryTest();
void ForwardDynamicsTrajectoryTest();
void SimulateControlTest();

#endif //MRTEST_H
